### PR TITLE
Adding tracing config to lambda functions. Security control CID-97

### PR DESCRIPTION
**Pull request by smartryanstewart**
Qualys remediation, CID-97 ensure that lambda function has tracing enabled.

### CODE REVIEW

**Comment by rraub** [comment]
Looks good, have we applied this on something yet to test it?  Also for this repo we're working off the `smartrent-master` branch because reasons, I switched the target branch for this PR and it looks like there are no conflicts.

**Comment by ryan-a-p-stewart** [comment]
Not yet but I will. I wanted to get eyes on it first though before I did.

**Comment by smartryanstewart** [comment]
Not yet but I will. I wanted to get eyes on it first though before I did.(OOPS wrong user at first.)

**Comment by smartryanstewart** [comment]
@rraub I moved the xray to the basic lambda policy document. I was having issues getting it from a different doc. Plus it kind of makes sense since it needs it based on infosec stuffs 🤷‍♂ Applied in dev.

**Review by rraub — APPROVED** [review]
LGTM

**Pull request merged**
